#+title: afspm

An Automation Framework for Scanning Probe Microscopy.

TODO Finish me

* Set up and compile protobuffer files

We use Google protobuffers to serialize/deserialize data between the various system components. We chose it over other options (e.g. JSON, YML/YAML) because:
- *It has multi-language/multi-platform support*: unlike pickle (default Python option), a compiled protobuf message can be sent/received by many languages, on any of the 3 main platforms (Windows, Linux, Mac).
- *It guarantees type-safety and avoids schema-violations*: we can be certain a message prepared does not break our schema, so we avoid unnecessary bugs / exception handling.

Now, there is one aspect that could be construed as either a pro or con: *protobuf messages are not human readable*. While human readability is, in principle, a huge plus, it tends to go hand-in-hand with a lack of type safety/easy schema violations. What we mean by this: a user can easily unintentionally send a broken message when they are able to create it with a simple text editor. Thus, we will *accept* this 'con' given our perceived larger 'pro'.

** Set up Google Protobuf Compiler
Download the protobuf compiler. The easiest way is to download the latest precompiled binaries from their releases: [[https://github.com/protocolbuffers/protobuf/releases][protobuf releases]].

Once downloaded, you will need to copy the executable and included well-known types to appropriate locations (so they are automatically detected):
- Copy/link/move the files in ./bin to /usr/local/bin.
- Copy/link/move the files in ./include to /usr/local/include.
** Compile the protobuf interfaces to your desired language
We will assume you are dealing in Python by default, since this whole project is Python-based. However, if you need to implement a particular component (e.g. DeviceController) in a different language, modify the below instructions for your required language.

#+begin_src bash
  cd /path/to/afspm/afspm/
  mkdir -p ./generated/python/
  protoc -I=./interfaces --python_out=./generated/python/ ./interfaces/*.proto
  # Fix absolute to relative imports
  sed -i ./generated/python/*_pb2.py -e 's/^import [^ ]*_pb2/from . \0/'
#+end_src
