<style>
  component {
    LineColor Gray
    LineThickness 0
  }
  .internal {
    BackgroundColor LightSteelBlue
  }
  .groupinternal {
    LineColor DarkBlue
    FontColor DarkBlue
    BackgroundColor AliceBlue
  }
  ' Consider LightCoral '
  .external {
    BackgroundColor Gold
  }
  .groupexternal {
    LineColor GoldenRod
    FontColor GoldenRod
    BackgroundColor LightGoldenRodYellow
  }

  .interface {
    BackgroundColor Gold|LightSteelBlue
  }

  .node {
    BackgroundColor SeaGreen
  }
  .socket {
    LineColor SeaGreen
    LineThickness 3
  }

  .message {
    BackgroundColor OldLace
    FontColor Sienna
    LineColor Sienna
    LineThickness 2
  }

  .required {
    LineThickness 1
    LineColor Black
  }

  .optional {
    LineColor Gray
  }

  .layout {
    LineColor Transparent
  }
  .center {
    HorizontalAlignment center
  }
  .left {
    HorizontalAlignment left
  }
  .right {
    HorizontalAlignment right
  }

  .color1 {
    BackgroundColor PHYSICAL
  }

  .color2 {
    BackgroundColor STRATEGY
  }

  .color3 {
    BackgroundColor MOTIVATION
  }

  .layout {
    borderColor Transparent
    backgroundColor Transparent
    fontColor Transparent
    stereotypeFontColor Transparent
  }
}

</style>

  skinparam componentStyle rectangle
  skinparam defaultTextAlignment center
  'skinparam linetype ortho

  ' wrapping stuff
  skinparam wrapWidth 300
  skinparam maxMessageSize 300

  'default line color is grey (to highlight required)'
  skinparam LineColor Gray

  hide stereotype
